name: Release

on:
  workflow_dispatch:
  push:
    tags: ["v*.*.*"]


env:
  LIBRIME_VER: "1.13.1"
  LIBRIME_HASH: "1c23358"
  RIME_LS_VER: "${{ github.ref_name }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
          targets: x86_64-unknown-linux-gnu,x86_64-pc-windows-msvc,x86_64-apple-darwin,aarch64-apple-darwin

      - name: Install dependencies
        run: |
          sudo apt install -y librime-dev p7zip
          pip3 install ziglang

      - name: Install cargo dependencies
        run: |
          cargo install --locked cargo-zigbuild
          cargo install --locked cargo-xwin

      - name: Download librime
        run: |
          mkdir librime
          wget https://github.com/rime/librime/releases/download/$LIBRIME_VER/rime-$LIBRIME_HASH-macOS-universal.tar.bz2 -O librime/mac.tar.bz2
          mkdir librime/mac
          tar xvjf librime/mac.tar.bz2 -C librime/mac
          wget https://github.com/rime/librime/releases/download/$LIBRIME_VER/rime-$LIBRIME_HASH-Windows-msvc-x64.7z -O librime/msvc.7z
          7z x librime/msvc.7z -olibrime/msvc

      - name: Build Linux
        run: |
          LIBRIME_INCLUDE_DIR=/usr/include LIBRIME_LIB_DIR=/usr/lib cargo zigbuild --target x86_64-unknown-linux-gnu.2.17 --release

      - name: Build Windows
        run: |
          LIBRIME_INCLUDE_DIR=./librime/msvc/dist/include LIBRIME_LIB_DIR=./librime/msvc/dist/lib cargo xwin build --target x86_64-pc-windows-msvc --release

      - name: Build macOS
        run: |
          LIBRIME_INCLUDE_DIR=./librime/mac/dist/include LIBRIME_LIB_DIR=./librime/mac/dist/lib cargo zigbuild --target universal2-apple-darwin --release

      - name: Archive
        run: |
          tar czvf target/rime-ls-$RIME_LS_VER-x86_64-unknown-linux-gnu.tar.gz -Ctarget/x86_64-unknown-linux-gnu/release/ rime_ls
          tar cjvf target/rime-ls-$RIME_LS_VER-universal2-apple-darwin.tar.bz2 -Ctarget/universal2-apple-darwin/release/ rime_ls
          7z a ./target/rime-ls-$RIME_LS_VER-x86_64-pc-windows-msvc.7z ./target/x86_64-pc-windows-msvc/release/rime_ls.exe 

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            target/rime-ls-$RIME_LS_VER-x86_64-unknown-linux-gnu.tar.gz
            target/rime-ls-$RIME_LS_VER-universal2-apple-darwin.tar.bz2
            target/rime-ls-$RIME_LS_VER-x86_64-pc-windows-msvc.7z
